<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<Version>7.5.0</Version>
		<TargetFramework>net6.0</TargetFramework>
		<LangVersion>preview</LangVersion>
		<EnableHarmony>true</EnableHarmony>
		<EnableModZip>false</EnableModZip>
		<EnableModDeploy>false</EnableModDeploy>
	</PropertyGroup>
	<ItemGroup>
		<Compile Remove="releases\**" />
		<EmbeddedResource Remove="releases\**" />
		<None Remove="releases\**" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Framework\Assets\HandMirror.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Framework\Assets\UI\HatButton.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Framework\Assets\UI\AccessoryButton.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Framework\Assets\UI\HairButton.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Framework\Assets\UI\OptionOneButton.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Framework\Assets\UI\OptionThreeButton.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Framework\Assets\UI\OptionTwoButton.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Framework\Assets\UI\PantsButton.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Framework\Assets\UI\ShirtButton.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.4.0" />
	</ItemGroup>

	<ItemGroup>
		<None Update="Framework\Assets\Local Pack\**">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Framework\Assets\UI\BodyButton.png">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Framework\Assets\UI\CheckButton.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Framework\Assets\UI\ExportButton.png">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Framework\Assets\UI\ShoesButton.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Framework\Assets\UI\SleevesButton.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Framework\Assets\UI\SleevesShoesButton.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="i18n\fr.json">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="i18n\ja.json">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="i18n\default.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="i18n\ko.json">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="i18n\ru.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="i18n\th.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="i18n\tr.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="i18n\uk.json">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="i18n\zh.json">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="manifest.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
